export const ResponseStyles = {
    h1: {
        fontSize: '2em',
        marginTop: '1.2em',
        marginBottom: '0.6em',
        lineHeight: '1.3',
        fontWeight: 'bold',
    },
    h2: {
        fontSize: '1.8em',
        marginTop: '1em',
        marginBottom: '0.5em',
        lineHeight: '1.35',
        fontWeight: 'bold',
    },
    h3: {
        fontSize: '1.6em',
        marginTop: '0.9em',
        marginBottom: '0.5em',
        lineHeight: '1.4',
        fontWeight: 'bold',
    },
    h4: {
        fontSize: '1.4em',
        marginTop: '0.8em',
        marginBottom: '0.5em',
        lineHeight: '1.5',
    },
    h5: {
        fontSize: '1.2em',
        marginTop: '0.7em',
        marginBottom: '0.5em',
        lineHeight: '1.6',
    },
    h6: {
        fontSize: '1em',
        marginTop: '0.6em',
        marginBottom: '0.5em',
        lineHeight: '1.6',
        fontWeight: 'bold',
    },
    p: {
        fontSize: '1em',
        marginBottom: '1em',
        lineHeight: '1.6',
    },
    ul: {
        paddingLeft: '20px',
        marginBottom: '1em',
        listStyleType: 'disc',
    },
    ol: {
        paddingLeft: '20px',
        marginBottom: '1em',
        listStyleType: 'decimal',
    },
    li: {
        marginBottom: '0.5em',
        lineHeight: '1.6',
    },
    blockquote: {
        margin: '1.5em 0',
        padding: '10px 20px',
        borderLeft: '4px solid #ccc',
        fontStyle: 'italic',
        background: '#f9f9f9',
        lineHeight: '1.6',
    },
    inlineCode: {
        background: '#f4f4f4',
        padding: '2px 4px',
        borderRadius: '4px',
        fontFamily: '"Courier New", monospace',
        fontSize: '0.9em',
        color: '#d63384',
    },
    codeBlock: {
        background: '#2d2d2d',
        color: '#ffffff',
        padding: '15px',
        borderRadius: '6px',
        overflowX: 'auto',
        fontSize: '0.95em',
        fontFamily: '"Courier New", monospace',
        lineHeight: '1.6',
    },
};

export const queryStyles = {
    h1: {
        fontSize: '1em',
        marginTop: '0.6em',
        marginBottom: '0.3em',
        lineHeight: '1.2',
        fontWeight: 'bold',
    },
    h2: {
        fontSize: '.9em',
        marginTop: '0.5em',
        marginBottom: '0.3em',
        lineHeight: '1.25',
        fontWeight: 300,
    },
    h3: {
        fontSize: '1em',
        marginTop: '0.4em',
        marginBottom: '0.3em',
        lineHeight: '1.3',
        // fontWeight: "bold",
    },
    h4: {
        fontSize: '.9em',
        marginTop: '0.4em',
        marginBottom: '0.3em',
        lineHeight: '1.35',
    },
    h5: {
        fontSize: '.90em',
        marginTop: '0.3em',
        marginBottom: '0.3em',
        lineHeight: '1.4',
    },
    h6: {
        fontSize: '0.8em',
        marginTop: '0.3em',
        marginBottom: '0.3em',
        lineHeight: '1.4',
        fontWeight: 'bold',
    },
    p: {
        fontSize: '.9rem',
        marginBottom: '0.5em',
        lineHeight: '1.4',
    },
    ul: {
        paddingLeft: '10px',
        marginBottom: '0.5em',
        listStyleType: 'disc',
    },
    ol: {
        paddingLeft: '10px',
        marginBottom: '0.5em',
        listStyleType: 'decimal',
    },
    li: {
        marginBottom: '0.3em',
        lineHeight: '1.4',
    },
    blockquote: {
        margin: '1em 0',
        padding: '5px 10px',
        borderLeft: '3px solid #bbb',
        fontStyle: 'italic',
        background: '#f5f5f5',
        lineHeight: '1.4',
        fontSize: '0.75em',
    },
    inlineCode: {
        background: '#eee',
        padding: '1px 3px',
        borderRadius: '3px',
        fontFamily: '"Courier New", monospace',
        fontSize: '0.7em',
        color: '#b34b7d',
    },
    codeBlock: {
        background: '#222',
        color: '#ddd',
        padding: '8px',
        borderRadius: '4px',
        overflowX: 'auto',
        fontSize: '0.8em',
        fontFamily: '"Courier New", monospace',
        lineHeight: '1.4',
    },
};
